const { Client } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');

const client = new Client();

client.on('qr', qr => {
    qrcode.generate(qr, { small: true });
    console.log('Scan QR code to log in.');
});

client.on('ready', () => {
    console.log('WhatsApp Bot is ready!');
});

client.on('message', message => {
    console.log(`Message received: ${message.body}`);
    if (message.body.toLowerCase() === 'hi') {
        message.reply('Hello! I am your bot 🤖');
    }
});

client.initialize();
